parameters:
#    main.example.class: PushT\Bundle\MainBundle\Example

services:
  validator.user:
          class: PushT\Bundle\MainBundle\Validator\UserValidator
          arguments:
              container: "@service_container"
              securityContext: "@security.context"
