parameters:
#    main.example.class: PushT\Bundle\MainBundle\Example

services:
  validator.user:
          class: PushT\Bundle\MainBundle\Validator\UserValidator
          arguments:
              container: "@service_container"
              securityContext: "@security.context"
  validator.push:
          class: PushT\Bundle\MainBundle\Validator\PushValidator
          arguments:
              container: "@service_container"
              securityContext: "@security.context"
  rabbitmq.push.service:
                  class: PushT\Bundle\MainBundle\Consumer\PushConsumer
                  arguments:
                      container: "@service_container"
     cache.job:
          class: PushT\Bundle\MainBundle\Cache\JobCache
          arguments:
              container: "@service_container"
     cache.push:
          class: PushT\Bundle\MainBundle\Cache\PushCache
          arguments:
              container: "@service_container"
